//@version=6
indicator('Session Box [odnac]', overlay = true)

grp_sessions = 'Session Boxes'
showAsia   = input.bool(true, 'Show Asia Session', group=grp_sessions)
showLondon = input.bool(true, 'Show London Session', group=grp_sessions)
showNY     = input.bool(true, 'Show NY Session', group=grp_sessions)
showSessionsOnWeekend = input.bool(false, 'Show Sessions on Weekend', group=grp_sessions)

showSessionsInTimeframe = timeframe.isintraday and timeframe.multiplier <= 60

colorAsia   = color.new(#F48FB1, 90)
colorLondon = color.new(#FFF59D, 90)
colorNY     = color.new(#90CAF9, 90)

asiaSession   = '0900-1300'
londonSession = '0800-1100'
nySession     = '0830-1130'

is_weekend = dayofweek == dayofweek.saturday or dayofweek == dayofweek.sunday

process_session(sessionTime, sessionColor, showToggle, sessionTimezone) =>
    var box sBox = na
    
    t = time(timeframe.period, sessionTime, sessionTimezone)

    is_new_session = not na(t) and na(t[1])
    is_in_session  = not na(t)

    bool canShowSession = showToggle and showSessionsInTimeframe and (showSessionsOnWeekend or not is_weekend)

    if canShowSession
        if is_new_session
            sBox := box.new(
                left = bar_index,
                top = high,
                right = bar_index,
                bottom = low,
                border_color = color.new(sessionColor, 100),
                bgcolor = sessionColor)

        if is_in_session and not na(sBox)
            box.set_right(sBox, bar_index + 1)
            box.set_top(sBox, math.max(box.get_top(sBox), high))
            box.set_bottom(sBox, math.min(box.get_bottom(sBox), low))

process_session(asiaSession,   colorAsia,   showAsia,   "Asia/Tokyo")
process_session(londonSession, colorLondon, showLondon, "Europe/London")
process_session(nySession,     colorNY,     showNY,     "America/New_York")
