//@version=6
indicator('Candle flow [odnac]', overlay = false)

// Settings
showSignal = input.bool(true, 'show bg signal', group = 'Settings')

// mother candle
var float refHigh = na
var float refLow  = na

if na(refHigh)
    refHigh := high
    refLow  := low

// detect inside bar
isInside = high <= refHigh and low >= refLow

// breakout condition
longSignal  = not isInside and high > refHigh
shortSignal = not isInside and low  < refLow
bothSweep   = longSignal and shortSignal

// detect trend bias
var int lastDirectionalTrend = 0

if longSignal and not bothSweep
    lastDirectionalTrend := 1
if shortSignal and not bothSweep
    lastDirectionalTrend := -1

// update mother candle
if longSignal or shortSignal or bothSweep
    refHigh := high
    refLow  := low

// color
color bullColor    = #089981
color bearColor    = #f23645
color bothColor    = color.white
color neutralColor = color.new(color.gray, 60)

candleColor = bothSweep    ? bothColor    :
              longSignal   ? bullColor    :
              shortSignal  ? bearColor    :
              neutralColor

plotcandle(open, high, low, close,
     color       = candleColor,
     wickcolor   = candleColor,
     bordercolor = candleColor,
     display     = display.all - display.status_line)

// signal
prevDir      = lastDirectionalTrend[1]
trueReversal = (prevDir == 1 and lastDirectionalTrend == -1) or
               (prevDir == -1 and lastDirectionalTrend == 1)

bgColor = trueReversal and lastDirectionalTrend == 1  ? color.new(bullColor, 90) :
          trueReversal and lastDirectionalTrend == -1 ? color.new(bearColor, 90) : na

bgcolor(showSignal ? bgColor : na)
