//@version=6
indicator("Divider [odnac]", overlay = true)

// ============================================================================
// DIVIDERS
// ============================================================================
showWeeklyDiver  = input.bool(true, 'Show Weekly Divider', group = 'Dividers')
showDailyDiver   = input.bool(true, 'Show Daily Divider', group = 'Dividers')
showH4Diver  = input.bool(false, 'Show H4 Divider', group = 'Dividers')
showH1Diver  = input.bool(false, 'Show H1 Divider', group = 'Dividers')

showWeeklyTimeframe = timeframe.isintraday and timeframe.multiplier >= 1 and timeframe.multiplier <= 240
showDailyTimeframe  = timeframe.isintraday and timeframe.multiplier >= 1 and timeframe.multiplier <= 60
showH4Timeframe = timeframe.isintraday and timeframe.multiplier >= 1 and timeframe.multiplier <= 30
showH1Timeframe = timeframe.isintraday and timeframe.multiplier >= 1 and timeframe.multiplier <= 30

is_new_week  = dayofweek == dayofweek.sunday and dayofweek[1] != dayofweek.sunday
is_new_day   = dayofmonth != dayofmonth[1]
is_new_h4  = hour != hour[1] and hour % 4 == 0
is_new_h1  = hour != hour[1]

if showWeeklyDiver and is_new_week and showWeeklyTimeframe
    line.new(bar_index, close + syminfo.mintick, bar_index, close - syminfo.mintick, color = color.rgb(255, 255, 255, 70), extend = extend.both, style = line.style_dashed)

if showDailyDiver and is_new_day and showDailyTimeframe
    line.new(bar_index, close + syminfo.mintick, bar_index, close - syminfo.mintick, color = color.rgb(255, 255, 255, 85), extend = extend.both, style = line.style_dashed)

if showH4Diver and is_new_h4 and not is_new_day and showH4Timeframe
    line.new(bar_index, close + syminfo.mintick, bar_index, close - syminfo.mintick, color = color.rgb(255, 255, 255, 85), extend = extend.both, style = line.style_dotted)

if showH1Diver and is_new_h1 and not is_new_day and showH1Timeframe
    line.new(bar_index, close + syminfo.mintick, bar_index, close - syminfo.mintick, color = color.rgb(255, 255, 255, 85), extend = extend.both, style = line.style_dotted)
