//@version=5
indicator("check list", overlay=true)

var table t = table.new(position.top_right, 2, 4, border_width = 1, border_color = color.gray)

if barstate.islast
    table.cell(t, 0, 0, "🕒 HTF", bgcolor=color.new(color.blue, 70), text_color=color.white, text_size=size.small)
    table.cell(t, 0, 1, "1. trend check", text_color=color.white, text_size=size.small, text_halign=text.align_left)
    table.cell(t, 0, 2, "2. OB & FVG check", text_color=color.white, text_size=size.small, text_halign=text.align_left)
    table.cell(t, 0, 3, "3. support & resistance check", text_color=color.white, text_size=size.small, text_halign=text.align_left)

    table.cell(t, 1, 0, "⚡ LTF", bgcolor=color.new(color.orange, 70), text_color=color.white, text_size=size.small)
    table.cell(t, 1, 1, "1. trend line check", text_color=color.white, text_size=size.small, text_halign=text.align_left)
    table.cell(t, 1, 2, "2. MSS check", text_color=color.white, text_size=size.small, text_halign=text.align_left)
    table.cell(t, 1, 3, "3. GAP check", text_color=color.white, text_size=size.small, text_halign=text.align_left)
