//@version=6
indicator('Volume Delta', overlay = false)

// M1 volume data
[l_close, l_high, l_low, l_vol] = request.security_lower_tf(syminfo.tickerid, '1', [close, high, low, volume])

// cal delta
float buyVol = 0.0
float sellVol = 0.0

int size = array.size(l_vol)

if size > 0
    for i = 0 to size - 1 by 1
        float lc = array.get(l_close, i)
        float lh = array.get(l_high, i)
        float ll = array.get(l_low, i)
        float lv = array.get(l_vol, i)
        float r = lh - ll

        if r > 0
            buyVol := buyVol + lv * (lc - ll) / r
            sellVol := sellVol + lv * (lh - lc) / r
            sellVol
        else
            buyVol := buyVol + lv * 0.5
            sellVol := sellVol + lv * 0.5
            sellVol

float delta = buyVol - sellVol

plot(delta, 'Delta', color = delta >= 0 ? color.new(color.teal, 15) : color.new(color.red, 15), style = plot.style_columns)
hline(0, color = color.new(color.gray, 40), linestyle = hline.style_dashed)
