//@version=6
indicator("SESSION BOXES", overlay = true, max_lines_count = 500, max_labels_count = 500, max_bars_back=5000)

grp_sessions = 'Session Boxes'
showAsia   = input.bool(true, 'Show Asia Session', group=grp_sessions)
showLondon = input.bool(true, 'Show London Session', group=grp_sessions)
showNY     = input.bool(true, 'Show NY Session', group=grp_sessions)
showStatus = input.bool(true, 'Show DST Status Table', group=grp_sessions)

showSessionsInTimeframe = timeframe.isintraday and timeframe.multiplier <= 60

colorAsia   = color.new(#F48FB1, 90)
colorLondon = color.new(#FFF59D, 90)
colorNY     = color.new(#90CAF9, 90)

is_summer_time() =>
    m = month(time, 'GMT-4')
    d = dayofmonth(time, 'GMT-4')
    w = dayofweek(time, 'GMT-4')
    isAfterMarchSt = m > 3 or (m == 3 and (d - w >= 8))
    isBeforeNovSt  = m < 11 or (m == 11 and (d - w < 1))
    isAfterMarchSt and isBeforeNovSt

autoSummer = is_summer_time()

asiaTime   = '0900-1300'
londonTime = autoSummer ? '1500-1800' : '1600-1900'
nyTime     = autoSummer ? '2100-0000' : '2200-0100'

process_session(sessionTime, sessionColor, showToggle) =>
    var box sBox = na
    t = time(timeframe.period, sessionTime, 'GMT+9')
    is_new_session = not na(t) and na(t[1])
    is_in_session  = not na(t)

    if showToggle and showSessionsInTimeframe
        if is_new_session
            sBox := box.new(left = bar_index, top = high, right = bar_index, bottom = low, 
                 border_color = color.new(sessionColor, 100), bgcolor = sessionColor)
        
        if is_in_session and not na(sBox)
            box.set_right(sBox, bar_index + 1)
            box.set_top(sBox, math.max(box.get_top(sBox), high))
            box.set_bottom(sBox, math.min(box.get_bottom(sBox), low))

process_session(asiaTime, colorAsia, showAsia)
process_session(londonTime, colorLondon, showLondon)
process_session(nyTime, colorNY, showNY)
